### PR TITLE
Add hex display to jtframe_debug, second attempt.

### PR DESCRIPTION
**Pull request by oscherler**
* I switched to a 4x5 pixels font to remove the multiplication by 5, which is now a left shift by 2;
* I changed the array indices to assignments outside the `always` block to remove the “inferring latch(es)” warnings.

### CODE REVIEW

**Comment by jotego** [comment]
Did you check if there are warnings related to this in the compilation?

**Comment by oscherler** [comment]
I need to update it, I messed up a conflict resolution and forgot a wire declaration. I’ll fix it tomorrow and include the warnings if any. To my knowledge there’s just a couple of truncation warnings because of the `vcnt[2:0] - 2` and `hcnt[2:0] - 3`, but I can fix those too.

**Comment by oscherler** [comment]
With this version, there are no warnings in `jtframe_debug` anymore.

**Comment by jotego** [comment]
This version looks better, doesn't have latches and it does not seem to affect compile time in a noticeable way.
Thank you.

**Comment by jotego** [comment]
By the way, let me comment the debug strategy in JTFRAME:
- Simple features for fast compilation: gfx_en, debug_bus, debug_view, save to SDRAM
- Complex features: the cheat engine, which includes a full CPU with access to two other debug buses (the status address and data buses) plus access to the first bank of the SDRAM
I think the simple features should not get much complicated than they are at the moment.

**Pull request merged**
