### PR TITLE
MiST: add direct SD Card upload feature

### PR DESCRIPTION
**Pull request by gyurco**
On the MiST hardware, the SD Card is directly connected to the FPGA,
thus it's possible to bypass the ARM MCU.
ROM loading will be about 4 times faster.

### CODE REVIEW

**Comment by jotego** [comment]
I have merged it but my MiST is refusing to power up now. It happens sometimes. I just leave it unconnected for a while...
A question: will this work with the "file open" option?
This PR is really nice. I was going to ask whether it was possible to speed up loading because CPS games take too long. I hope it works ok once my MiST accepts its fate and powers up!

**Comment by gyurco** [comment]
Yes, it's also applies to the "F" option, too. Only one caveat: now the transfer size is in terms of cluster size, if you rely on the address to determine the file size, it'll fail. Also it'll transfer garbage at the end if the file size is not the multiple of the FAT cluster size.
Hope not this patch broke your MiST :)

**Comment by jotego** [comment]
I have been able to try it now.
For some reason it seems to break the cores completely. Not even will the OSD be displayed. I have taken it to a different branch ([fast-load](https://github.com/jotego/jtframe/tree/fast-load)) in case you have time to try it.
What you tell me about transfering garbage at the end is a problem, actually. Like the CPS core will copy the first 23 bytes of each 32 bytes downloaded internally to configure the CPS-B registers. It is done continually but only the last packet will contain the right values. It is easy to do it that way and safe, provided no garbage comes after the right 32 bytes.
Many cores do rely on the address of the data to perform sorting operations on the fly too.
So I wonder if this may not be compatible with all the IP I already have.

**Comment by gyurco** [comment]
It worked for me in 1942,1943,Commando,GnG, I'll try the other branch at home.

Btw, you don't have to revert the whole thing, just you can set ROM_DIRECT_UPLOAD to 0 for user_io, then it won't send the flag to turn on the direct transfer in the firmware.
There are some other updates that could be useful, like the core_mod signal to determine the MOD value, or no_csync which is a hint that the user don't want composite sync in 15kHz.

Since it's not really possible to stop the SD Card transferring a whole sector, the garbage problem will there. However the real size of the file is transferred to the FPGA already, I can make it visible via an output signal in data_io. Then you can drop bytes when the size is exceeded (or the dropping can be integrated into data_io).

**Comment by jotego** [comment]
I have disabled the direct load (using the parameter ROM_DIRECT_UPLOAD) and it worked correctly. So at least the other benefits are there. I have uploaded it to github.

My firmware is from November... Let me update.

**Comment by jotego** [comment]
After the firmware update, it worked for 1943. It is really fast. Speaking of firmware... MiST used to send the file in the core_dir/core_name.rom to the core but that doesn't seem to happen anymore and I always have to load it manually. It's the same for this firmware update. Did something change in MiST specs?

If you could stop the **ioctl_wr** signal once the file size has been met, that'd be perfect. I suppose that up to that point **ioctl_addr** values are valid and starting from zero.

**Comment by gyurco** [comment]
I never knew it worked from core_dir. When did you see that last time?
It's working either from root, or the same directory as the RBF (but the later is obviously not usable with the USB Blaster).
I can stop ioctl_wr, and also incrementing ioctl_addr, too. That way it'll behave the same way as without the direct upload (except garbage bytes will read behind the scene - but that doesn't matter).

**Pull request merged**
